# Generated by Django 4.2.16 on 2024-11-20 13:32

import apps.user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cover_image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=apps.user.models.user_cover_image_directory),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=apps.user.models.user_profile_image_directory),
        ),
    ]
